### ISSUE TITLE
Tailwindcss 3.0 focus:outline-none doesn't work ，please support 3.0 Thank you

### ISSUE THREAD

**Issue by 8108905** [tailwindlabs/tailwindcss-forms#100]
### What version of @tailwindcss/forms are you using?

last version

### What version of Node.js are you using?

last version

### What browser are you using?

Chromne

### What operating system are you using?

macOS

### Reproduction repository

none

### Describe your issue

Tailwindcss 3.0 focus:outline-none doesn't work
 
  <input type="text" class="focus:outline-none">

please support 3.0 Thank you

**Comment by reinink** [comment]
Hey there!

So I just gave this a try, and `focus:outline-none` is working for me. See here:

https://play.tailwindcss.com/nTx0SXR4AZ

However, it's possible that you're getting stuck because the forms plugin uses rings for outline styles by default, not the new outline utilities. This is because the new outline utilities don't quite have full browser support yet — specifically they don't follow the border-radius in Safari.

You can disable the ring utilities on hover using `focus:ring-0`.

Hope that helps 👍

**Comment by binaryartifex** [comment]
whats frustrating about the current implementation is the fact that im forced into using the focus: pseudo element. I use react-aria for my components and rely on the focus/hover/pressed/disabled/etc hooks to determine what styling to apply for maximum compatibility across a plethora of systems and devices.

i would of hoped something like this works but it doesn't. so i have to insert the `focus-visible:ring-primary-500` in the className and remove the focus hook implementation

```typescript
  const { focusProps, isFocusVisible } = useFocusRing({
    autoFocus: inputProps.autoFocus,
  });

  return (
    <input
      {...mergeProps(inputProps, focusProps)}
      className={classNames(
        "form-checkbox w-6 h-6 rounded-md text-primary-500",
        "focus:ring-transparent transition-all ease-in-out",
        isFocusVisible && "ring-2 ring-primary-500",
      )}
      ref={inputRef}
    />
  );
```
