### ISSUE TITLE
Cannot find "/dist/forms.min.css" in @tailwindcss/forms@0.5.0

### ISSUE THREAD

**Issue by ishaiavrahami** [tailwindlabs/tailwindcss-forms#110]
### What version of @tailwindcss/forms are you using?

latest

### What version of Node.js are you using?

none

### What browser are you using?

chrome

### What operating system are you using?

macos

### Reproduction repository

none

### Describe your issue

Hello, im using in my HTML the following cdn `https://unpkg.com/@tailwindcss/forms@latest/dist/forms.min.css` and it doesn't seem to be rendering the CSS. Is it possible to maintain the Forms CSS CDN?

**Comment by authcompanion** [comment]
+1 - was depended on the forms css cdn as well and now broken due to 404. 
Needing to pin to earlier version.

**Comment by reinink** [comment]
Hey there!

The CDN version was removed in `v0.5.0`, since this version was designed to be used with Tailwind CSS v3, which now also does not ship with a CDN version now that the JIT engine has replaced the previous AOT (ahead-of-time) engine.

Tailwind CSS v3 is intended be used as part of a build process, and the forms plugin works the same way, so that's what I'd recommend doing if at all possible.

Of course, you're welcome to continue using the previous `v0.4.0` CDN version, as @authcompanion suggested:

```
https://unpkg.com/@tailwindcss/forms@0.4.0/dist/forms.min.css
```

Also, I'd recommend not using the `@latest` flag when including an asset from a CDN, as it can change at anytime and break your app. It's much better to use a fixed version, as it will never change.

Hope that helps! 👍

**Comment by authcompanion** [comment]
A feat request for tailwind css v4 - works without build process 👍 It is the future!

**Comment by ishaiavrahami** [comment]
Update - Use the new `<script src="https://cdn.tailwindcss.com?plugins=forms"></script>` to render tailwind + forms plugin
