### ISSUE TITLE
Style date placeholders to match standard placeholders

### ISSUE THREAD

**Issue by hailwood** [tailwindlabs/tailwindcss-forms#38]
The placeholders on date inputs don't respect the standard placeholder attribute.
It would be great if we could have the pseudo elements styled so they match the placeholder e.g. changing

```
'input::placeholder, textarea::placeholder'
```

to

```
'input::placeholder, textarea::placeholder, ::-webkit-datetime-edit'
```

There's a bit more to it (e.g. the firefox placeholders)

**Comment by thecrypticace** [comment]
I spent an absolutely ridiculous amount of time looking into this many months ago for a personal project. I came to the conclusion that it's not simple. There are solutions but they all have problems. :/

I created a Tailwind Play with comments in the CSS and a preview of what works and what does not: https://play.tailwindcss.com/IV31S1G6iv?file=css

**Comment by reinink** [comment]
Hey! So I just spent more time that I'd like to admit trying to figure this out, and I've ultimately come to the unfortunate conclusion that this can't be fixed in Safari. Let me walk you through what I've learned...

What I've come to realize is that browsers don't consider the date input empty state "value" (which is "YYYY-MM-DD" in Chrome and Firefox, and the current date in Safari) to be a placeholder, even though it very much has a placeholder vibe to it. Because it's not a placeholder, it can't be styled using the `::placeholder` pseudo selector in CSS.

So, what can we do?

Well, before we get into Safari, let's start by looking at Chrome and Firefox. These browsers always show the "YYYY-MM-DD" empty value in the same color as the date input's text color. So, applying a text color like `text-red-500` results in this:

```html
<input type="date" class="text-red-500">
```

<img width="263" alt="image" src="https://github.com/tailwindlabs/tailwindcss-forms/assets/882133/eeb116cd-d04f-4c99-882e-a3c5adc90b65">

Trying to apply a placeholder color results in no changes to the "YYYY-MM-DD" empty value:

```html
<input type="date" class="placeholder:text-red-500">
```

<img width="267" alt="image" src="https://github.com/tailwindlabs/tailwindcss-forms/assets/882133/efc129fb-006d-400f-b02b-d38a431ac16d">

There really isn't any concept of a date input placeholder in Chrome and Firefox.

Where this gets complicated is in Safari. Safari doesn't show "YYYY-MM-DD" for the empty state, but instead shows today's date, but in a muted placeholder style:

<img width="231" alt="image" src="https://github.com/tailwindlabs/tailwindcss-forms/assets/882133/5755db49-6a36-45b4-a7e5-6c9cc1d8f483">

Like in Chrome and Firefox, adding a placeholder is not possible but adding a text color is:

```html
<input type="date" class="text-red-500">
```

<img width="227" alt="image" src="https://github.com/tailwindlabs/tailwindcss-forms/assets/882133/9485a628-1976-4593-a1e2-2135bc511cff">

However, when you set a text color, Safari automatically adjusts the text brightness to make sure that the default date input (today's date) is muted enough, making sure to distinguish it from a real value. However, you have no control over the exact color that Safari chooses here. It has some type of algorithm and metrics it uses to set this, and despite all my best efforts I was unable to get it to use the placeholder color of my choosing.

Basically Safari takes whatever color you set for the date input text color, and then reduces it by about 50%. Even if you set it to straight up black, it's still pretty muted:

<img width="231" alt="image" src="https://github.com/tailwindlabs/tailwindcss-forms/assets/882133/5755db49-6a36-45b4-a7e5-6c9cc1d8f483">

And what's really weird is that, depending on the color you choose, it might even just straight up throw that away and use blue instead:

```html
<input type="date" class="text-slate-950">
```

<img width="229" alt="image" src="https://github.com/tailwindlabs/tailwindcss-forms/assets/882133/f4f54c01-1b0e-4c07-bced-07aa20c93071">

## Using the `-webkit-datetime-*` pseudo classes

Now Safari does provide the `-webkit-datetime-*` pseudo classes, allowing you to style each individual part of the date, and what's interesting is that this only seems to impact the date input when there is an actual value, not the empty state. So, at first I thought that we could potentially use this to style the empty "placeholder" color independently of the text color:

```html
<input type="date" value="1983-06-02" />
<input type="date" />
```

```css
/* set the default date text color */
input[type="date"]::-webkit-datetime-edit-year-field,
input[type="date"]::-webkit-datetime-edit-month-field,
input[type="date"]::-webkit-datetime-edit-day-field {
  color: theme(colors.gray.700);
}

/* set the slashes to gray 700 */
input[type="date"]::-webkit-datetime-edit-text {
  color: theme(colors.gray.700);
}

/* adjust the placeholder style to be as dark as possible */
input[type="date"] {
  color: black;
}
```

<img width="443" alt="image" src="https://github.com/tailwindlabs/tailwindcss-forms/assets/882133/8b0f08ec-8d85-4086-b88c-7b5a9618fd87">

And honestly, when you first see the results here it actually looks like we've accomplished something. Unfortunately, in reality Safari has chosen an empty "placeholder" state color that doesn't really match what we might use for our other placeholder colors. For example, imagine we want a placeholder color of `text-gray-500` for our inputs:

<img width="445" alt="image" src="https://github.com/tailwindlabs/tailwindcss-forms/assets/882133/fcb5e297-1edd-4004-b3aa-94113d91bd5a">

Notice here how the date input placeholder doesn't match with the text input (gray-500) placeholder. And if you compare this to how things look today, you can see that it's hardly any different — we haven't meaningfully improved things despite all our best efforts:

<img width="451" alt="image" src="https://github.com/tailwindlabs/tailwindcss-forms/assets/882133/e6d28350-5395-4bde-b002-a21748ef0c5c">


## Hacking validation

Also, just in case anyone looks at this issue in the future, some folks suggested using client-side validation in conjunction with the `-webkit-text-fill-color` property to solve this. The `-webkit-text-fill-color` property is interesting because it cannot have an opacity, so it forces the date input color. For example:

```html
<div><input type="date" required /></div>
<div><input type="date" value="1983-06-02" required /></div>
```

```css
input[type="date"] {
  color: theme(colors.gray.900);
}

input[type="date"]:invalid {
  -webkit-text-fill-color: theme(colors.gray.500);
}
```

<img width="242" alt="image" src="https://github.com/tailwindlabs/tailwindcss-forms/assets/882133/94b895dd-2b8a-4ad9-a17c-cfef158d6ee5">

While this kind of works, it's really hacking the `:invalid` psuedo selector for something it's not intended to be used with. For example, if the date input is invalid for a different reason — maybe it has a `max` validation rule on it — you'll end up seeing the fake placeholder styles.

(Oh and if you're wondering if you can use the `-webkit-text-fill-color` property in my first solution to get around this, unfortunately nope, as this property takes precedence over the `color`, meaning there is no way to target the two date input states independently and you'll just get the `-webkit-text-fill-color` in both states.)

## Conclusion

So ultimately, while it is possible to slightly affect the color of Safari's empty value "placeholder" color, it's hardly a perfect science and doesn't lead to super great results. Given all that, I am inclined to just leave things as they are and close this issue for now. Who knows, maybe Safari improves the APIs here in the future and gives us more control, but I am not holding my breath 😅

@hailwood Thanks either way for sharing — it would have been nice if we could find a reliable way to solve this, but some things on the web just are what they are.

**Comment by hailwood** [comment]
This has been a wild ride, I could feel the "I've got it!" excitement rise and fall reading through all that. Thanks for looking into this and sharing @reinink!

**Comment by leevigraham** [comment]
My solution based on previous work here and more experiments.

`-webkit-text-fill-color:` supports opacity when using `rgba` which means we can use a consistent colour. The downside here is that the input with the value is also transparent.

![image](https://github.com/tailwindlabs/tailwindcss-forms/assets/25124/79f7bfda-bfcb-474f-bed7-a4d204b97ab7)

The next part requires toggling a 'js' and `no-value` class on the input. We rely on the `.js` class to add our css overrides without effecting the input for non-js users. The final trick is to add a `change` event listener to the input which toggles the `no-value` class. If the `no-value` and `js` classes are applied set the `-webkit-text-fill-color:` to a transparent version.

![image](https://github.com/tailwindlabs/tailwindcss-forms/assets/25124/a6fa49ba-7eeb-4bd5-bbc0-db1df5024a33)

Here's the pen https://codepen.io/leevigraham/pen/VwRpRpv

This is non tailwind example but I'm sure toggling tailwind classes could achieve the same thing.

**Comment by alfonsrv** [comment]
Sooo, what's the best practice for this use case now?

I mean interesting behavior insight on especially Safari and all, but I feel like I have more questions than before I started reading this issue. 🤔

**Comment by adamwathan** [comment]
> Sooo, what's the best practice for this use case now?

Just deal with it looking bad or use a JS-based date picker :/ The web sucks!
