### ISSUE TITLE
Support for 'disabled' attribute 

### ISSUE THREAD

**Issue by robrechtme** [tailwindlabs/tailwindcss-forms#41]
Hi!

First of all, love the plugin! 
Is there any reason why the `disabled` attribute is _ignored_?
There is no visual difference anymore between the two:

https://play.tailwindcss.com/uEon0s582K?file=config

I can look into making a PR, if you think that would be a nice addition.

**Comment by frederikhors** [comment]
> I can look into making a PR

please

**Comment by adamwathan** [comment]
It's not really that it's ignored, just that we don't have to do anything special to make disabled states _styleable_. This plugin isn't designed to make forms automatically look good or anything, just make them work more easily with utilities. How you want things to look when they are disabled is hard to generalize, the styles would be different in each project.

The recommended approaches to styling disabled form elements are either:

1. Just add utilities whenever you add the disabled attribute, usually with JS. Might look something like this:

    ```jsx
    <input className={`... ${formDisabled ? 'opacity-50' : ''}`} disabled={formDisabled} />
    ```

2. Use Tailwind's [`disabled` variant](https://tailwindcss.com/docs/hover-focus-and-other-states#disabled) (not enabled in Tailwind by default)

    ```html
    <input class="... disabled:opacity-50" disabled />
    ```

No plans to add disabled styles by default as I think that would actually make it harder for people to use _custom_ disabled styles, since they would be forced to enable the `disabled` variant to defeat the default disabled styles. Hope that makes sense.

**Comment by robrechtme** [comment]
Thank you for your insights. I didn't know if it was intentional or not, but now that you've told me the reasoning behind it I totally understand.
