### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by jeroenvanrensen** [tailwindlabs/tailwindcss-forms#46]
Hi everyone,

I tried to install Tailwind Forms but nothing changes to my checkboxes.

This is what I did:

1. `npm install @tailwindcss/forms`
2. Add `require('@tailwindcss/forms')` to the plugin section of `tailwind.config.js`
3. Run `npm run dev` (Laravel)

I didn't get any errors, but nothing changes in my browser.

And according to the docs I did not have to change anything to my HTML, just at the `type="checkbox"` attribute.

Does anyone know what happens?

**Comment by leesmith** [comment]
Are you using purge in your tailwind config? If so, disable it temporarily and try it again. This is the [issue](https://github.com/tailwindlabs/tailwindcss-forms/issues/43) I'm having anyway.

**Comment by jeroenvanrensen** [comment]
@leesmith I did but removed it, however, it still does to work. This is my complete `tailwind.config.js` file:

```javascript
module.exports = {
    purge: [],
    darkMode: false,
    theme: {
        extend: {}
    },
    variants: {
      extend: {}
    },
    plugins: [
        require('@tailwindcss/forms'),
    ]
}

```

**Comment by websolutely** [comment]
What I found out:
my app.css does not change running npm dev or prod with or without using require('@tailwindcss/forms') in the tailwind.config.js file. Removing the purge part also does not have an effect.

So to solve this, because I really need this quickly, I copied 

https://tailwindcss-forms.vercel.app/dist/forms.css 

to my resources/dist/file and imported it in the resurces/app.css:

@import 'dist/forms.css';

But this did not work either. So I removed the default color in 109 (There are more colors. but this is the checkbox color I need and it should work with all the other colors, too). This works with dev, prod AND purge and so far I have a working tw2/forms solution.

I know that it is not a good workaround, but after some hours I was desperate. Would be great, if someone could fix this, so we can use it correctly

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you try and reproduce it on https://play.tailwindcss.com and share it?

Here is an example: https://play.tailwindcss.com/4UAxn4jVPR
The source of our demo (https://tailwindcss-forms.vercel.app) can be found here: https://github.com/tailwindlabs/tailwindcss-forms/blob/master/index.html

**Comment by jeroenvanrensen** [comment]
@RobinMalfait I'm really confused now, I tried but in the playground it does work

**Comment by jeroenvanrensen** [comment]
I found it! Yet another stupid fault of mine... I forgot to update the assets on the main Laravel installation because I'm creating a Laravel package. However, thanks for your help!
