### ISSUE TITLE
Forms vs Custom Forms

### ISSUE THREAD

**Issue by chrisrowe** [tailwindlabs/tailwindcss-forms#51]
I was under the impression that this repo effectively replaces the custom forms repo at https://github.com/tailwindlabs/tailwindcss-custom-forms

I can see the approach is different and that's totally fine but I'm finding myself missing the ability to style checkboxes etc with more control. The defaults and flexibility that custom forms gave was heaven despite it not being truly "utility" based as per Tailwind.

@adamwathan Could you please advise on your vision here so we can taylor our approach, should we be using forms **and** custom forms to get where we want, or is the longer term plan to abandon custom forms and bring in some of that fancier stuff into this repo in future perhaps?

**Comment by adamwathan** [comment]
Custom forms is deprecated and not supported in Tailwind 2. What sort of customizations are you having issues with? You should be able to customize things however you want by just opening up your CSS file and writing the CSS you need. I found that the customization API in custom forms was terrible, just a worse and more confusing version of simply writing CSS which is why we've opted to not offer any API like that with this library and instead encourage people to just add their own base styles that provide any desired overrides.

**Comment by chrisrowe** [comment]
Thanks for the prompt response. This makes total sense, I guess I was getting hung up on the ability to set checkbox icons and colors etc but I'll defer to CSS to handle those edge cases. Cheers!
