### ISSUE TITLE
Readme says Tailwind v2 is in alpha

### ISSUE THREAD

**Issue by edjw** [tailwindlabs/tailwindcss-forms#7]

**Comment by mustafa-online** [comment]
I updated it via a pull request.

**Comment by ikornienko** [comment]
Noticed also that alpha version is used in [package.json](https://github.com/tailwindlabs/tailwindcss-forms/blob/master/package.json#L23). Yes, it's a dev dependency, yet it does create a sense that this plugin wasn't tested for compatibility with the final tailwindcss v2.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

This has been fixed in https://github.com/tailwindlabs/tailwindcss-forms/commit/4e2b13db1c83c9a67c328bc30a6dfc9dfe73a6d6

---

@ikornienko feel free to provide a PR for that. Otherwise it will be fixed once we bump the version. It should still be compatible with the latest version of Tailwind.
