### ISSUE TITLE
Forms plugin don't respect new fontSize base

### ISSUE THREAD

**Issue by ddiazepam** [tailwindlabs/tailwindcss-forms#77]
### What version of @tailwindcss/forms are you using?

0.2.1

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/ddiazepam/tailwindformsbug

### Describe your issue

Forms plugin don't respect overwritten font size in tailwind.config.js.

I have overwritten fontSize base like this in tailwind.config.js:

```js
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    purge: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],

    theme: {

        fontSize: {
            'xs': '.75rem',
            'sm': '.875rem',
            'tiny': '.875rem',
            'base': '.9375rem',
            'lg': '1.125rem',
            'xl': '1.25rem',
            '2xl': '1.5rem',
            '3xl': '1.875rem',
            '4xl': '2.25rem',
            '5xl': '3rem',
            '6xl': '4rem',
            '7xl': '5rem',
           },

        minWidth: {
            '0': '0',
            '1/4': '25%',
            'full': '100%',
        }
    },

    variants: {
        extend: {
            opacity: ['disabled'],
            cursor: ['disabled'],
            display: ['group-hover'],
            width: ['hover'], 
        },
    },

    plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],

};
```

But forms plugin still use default value from tailwind defaultTheme. Shouldn't it use new values?

**Comment by adamwathan** [comment]
Hey! By design we don't pick up values like this from your config unfortunately, just makes it a much trickier thing to build and hard to understand all of the possible situations it needs to handle. If you are customizing your base font size and want the form styles to update to match, I would recommend just customizing the form styles with your own custom CSS like mentioned here:

https://github.com/tailwindlabs/tailwindcss-forms/issues/33#issuecomment-807883605

Hope that helps!
