### ISSUE TITLE
Strategy class produces errors

### ISSUE THREAD

**Issue by MotionPhix** [tailwindlabs/tailwindcss-forms#79]
### What version of @tailwindcss/forms are you using?

0.2.1

### What version of Node.js are you using?

v14. 16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### Reproduction repository

None

### Describe your issue

![Screenshot (24)](https://user-images.githubusercontent.com/59722054/132942825-64518838-7ea9-4e73-9c25-1583f6f86a50.png)

With reference from the screenshot above, I am having issues with tailwindcss/forms plugin when I opt to use the class strategy. Using it with default configuration works fine but I'm using another UI library for forms and I wanted to only use tailwindcss/forms on a few inputs (checkbox to be precise), but the class strategy produces `TypeError: require(....) is not a function at Object.<anonymous>`. What could be the issue?

**Comment by adamwathan** [comment]
Hey! I can't reproduce this, here's a repository I created showing it working as expected:

https://github.com/adamwathan/tailwindcss-forms-class-strategy-test/tree/main

In order to keep our issues tidy and under control, we close issues when no reproduction is provided, especially when we are unable to reproduce ourselves after taking the time to try and recreate what's been described.

If the demo I've created above doesn't fix your problem, can you please open a new issue and include a reproduction so we can more easily troubleshoot using your exact code?

**Comment by jean-francois-labbe** [comment]
I had the same issue, the `@tailwindcss/forms` package version was `0.2.1`
Upgrading to `0.3.3` fixed it

**Comment by tance77** [comment]
You spelt Strategy wrong @MotionPhix missing an r
